chat/urls.py
from django.urls import path
from . import views

app_name='chat_zone'

urlpatterns = [
    path('', views.index, name='index'),
    path('ajax/upload-voice-note/', views.upload_voice_note, name='upload_voice_note'),
    path('ajax/message-read/', views.message_read, name='message_read'),
    path('public/<str:room_name>/', views.public_room, name='public_room'),
    path('private/<str:room_name>/', views.private_room, name='private_room'),
    path('ajax/111/', views.check_fetch, name='check_fetch')
]

mysite/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('', include('chat.urls', namespace='chat_zone')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

chat/views.py
from django.shortcuts import render, redirect
from .models import GroupChatRoom, ChannelVilla, ChannelBindingIdentity, Messages, MarkAsRead
from django.contrib import messages
from accounts.models import PhoneBook
import json
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from accounts.models import CurrentlyBindedContact, Profile
from django.http import JsonResponse
import os
import base64
from django.core.files.uploadedfile import SimpleUploadedFile
from .tasks import async_mark_as_read_views
from time import sleep

# Create your views here.
@login_required
def index(request):
    connected_channels = ChannelBindingIdentity.objects.filter(connected_receiver=request.user).order_by('-created_on')
    # print(connected_channels)
    public_chat = []
    private_chat = []
    for ch in connected_channels:
        if ch.channel_name_type == 'public':
            public_chat.append(ch.channel_name)
        if ch.channel_name_type == 'private':
            private_chat.append(ch.channel_name.channel_name_main)
    public_rooms = GroupChatRoom.objects.filter(channel_name__in=public_chat)
    # print(request.user.id)
    # print(private_chat)
    # print(request.user.profile.home_channel_name)
    user_list = []
    cbc_qs = CurrentlyBindedContact.objects.filter(
        app_runner=request.user,
        channel_name__in=private_chat)
    for cbc in cbc_qs:
        profile = Profile.objects.get(home_channel_name=cbc.contact_channel)
        user_list.append(profile.user)
    private_rooms = User.objects.filter(username__in=user_list)
    # print(request.user.profile.home_channel_name)
    content = {
        'connected_channels':connected_channels,
        'public_rooms':public_rooms,
        'private_rooms':private_rooms,
        'home_channel_name':request.user.profile.home_channel_name
    }
    return render(request, 'chat/home.html', content)


@login_required
def public_room(request, room_name):
    own_user_number = User.objects.get(username=request.user).username
    try:
        channel_name = ChannelVilla.objects.get(channel_name_main=room_name)
        group_info = GroupChatRoom.objects.get(channel_name=channel_name)
    except (ChannelVilla.DoesNotExist, GroupChatRoom.DoesNotExist):
        messages.error(request, 'Chat room is unavaiable to you')
        return redirect('chat_zone:index')

    try:
        room_mates = ChannelBindingIdentity.objects.filter(channel_name=channel_name)
    except:
        messages.error(request, 'Could not get members of chatroom')
        # return redirect('chat_zone:index')
    rm_list = []
    rm_list.append('You')
    for room_mate in room_mates:
        try:
            user = User.objects.get(username=room_mate.connected_receiver)
            ph_book = PhoneBook.objects.get(number__iexact=str(user.username))
            if user != request.user:
                rm_list.append(str(ph_book.contact_name))
        except PhoneBook.DoesNotExist:
            if user != request.user:
                rm_list.append(str(room_mate.connected_receiver))
    home_channel_name = Profile.objects.get(user=request.user).home_channel_name
    group_members = str(rm_list[0:3])
    group_members = group_members.replace('[','').replace(']','').replace("'","")
    # chat_messages = Messages.objects.filter(channel_name=ch_name).order_by('created_on')[:20]
    # try:
    ph_list = PhoneBook.objects.filter(phone_owner=request.user).values().values_list('contact_name', 'number')
    print(json.dumps(list(ph_list)))

    ch_name = ChannelVilla.objects.get(channel_name_main=room_name)
    chat_messages = Messages.objects.filter(channel_name=ch_name)
    # messages = reversed(room.messages.order_by('-created_on')[:50])

    # msr = MarkAsRead.objects.filter(channel_name=ch_name, message_delivered=False, read_by=request.user)
    # for mr in msr:
    #     mr.message_unread = True
    #     mr.message_delivered = True
    #     mr.save()

    async_mark_as_read_views.delay(room_name, request.user.username)

    # except:
    #     chat_messages = ''

    if len(rm_list) > 3:
        group_members = '%s...'%group_members
    content = {
        'group_members': group_members,
        'room_name': room_name,
        'group_name': group_info,
        'own_user_number': own_user_number,
        'home_channel_name': home_channel_name,
        'chat_messages': chat_messages,
        'phonebook': json.dumps(list(ph_list))

    }
    return render(request, 'chat/public_chat_space.html', content)


@login_required
def private_room(request, room_name):
    # name_of_your_function.delay(10)
    try:
        local_storage = CurrentlyBindedContact.objects.get(app_runner=request.user, contact_channel=request.user.profile.home_channel_name, channel_name=room_name)
    except CurrentlyBindedContact.DoesNotExist:
        # local_storage = CurrentlyBindedContact.objects.get(app_runner=request.user, channel_name=room_name)
        try:
            local_storage = CurrentlyBindedContact.objects.get(app_runner=request.user, channel_name=room_name)
        except:
            messages.error(request, 'Unauthorized access to room')
            return redirect('chat_zone:index')
    profile = Profile.objects.get(home_channel_name=local_storage.contact_channel)
    personal_channel_add = Profile.objects.get(user=request.user)
    if profile.online != True:
        status = profile.last_seen_algorithm
    else:
        status = 'Online'
    if profile.contact_name is None:
        contact_name = profile.mobile
    else:
        contact_name = profile.contact_name
    own_user_number = User.objects.get(username=request.user).username
    # print(personal_channel_add.home_channel_name)
    # print(local_storage.contact_channel)
    # chat_message = chat_message[chat_message:20]
    # chat_messages = Messages.objects.filter(channel_name=ch_name).reverse().order_by('-created_on')[0:20]
    # print(json.dumps(list(ph_list)))
    ph_list = PhoneBook.objects.filter(phone_owner=request.user).values().values_list('contact_name', 'number')
    chat_messages = Messages.objects.filter(channel_name__channel_name_main=room_name)
    # messages = reversed(room.messages.order_by('-created_on')[:50])
    # print(chat_messages)
    # try:
    #     ch_name = ChannelVilla.objects.get(channel_name_main=room_name)
    #     msr = MarkAsRead.objects.filter(channel_name=ch_name, message_read=False, read_by=request.user)
    #     for mr in msr:
    #         mr.message_read = True
    #         mr.message_delivered = True
    #         mr.save()
    # except:
    #     chat_messages = ''
    # async_mark_as_read_views.delay(room_name, request.user.username)

    content = {
        'room_name': room_name,
        'status': status,
        'own_user_number': own_user_number,
        'home_channel_name': personal_channel_add.home_channel_name,
        'room_mate_home_channel_name': local_storage.contact_channel,
        'contact_name': contact_name,
        'profile_picture': profile.cover_image,
        'chat_messages': chat_messages,
        'phonebook': json.dumps(list(ph_list))
    }
    return render(request, 'chat/private_chat_space.html', content)

@login_required
def upload_voice_note(request):
    if request.is_ajax and request.method == 'POST':
        channel_name = request.POST['channel_name']
        message_id = request.POST['message_id']
        media_file = request.FILES['voice_note']
        print(type(media_file))
        print(channel_name)
        print(message_id)
        # with open("voice_note.wav", "wb") as fh:
        #     fh.write(base64.decodebytes(media_file))

        # print(fh)

        # suf = SimpleUploadedFile('uploaded_file.wav', image_output.read(), content_type='audio/wav')
        # print(suf)

        # filename, ext = os.path.splitext(self.event['media_file'].lower())
        # filename = "%s.%s" %(slugify(filename), timezone.now())
        # hs_index = hashlib.md5(filename.encode()).hexdigest()
        # message = Messages.objects.create(
        #     sent_by=request.user,
        #     media = '🎙 Voice note',
        #     media_file = text_data_json['message'],
        #     file_type = text_data_json['file_type'],
        #     channel_name = ch_name,
        #     message_id = text_data_json['message_id'],
        #     # message_state = None,
        # ).save()
        # msr = MarkAsRead.objects.create(
        #     message = message,
        #     channel_name = ch_name,
        #     read_by = self.scope['user']
        # ).save()
        # message.message_unread = msr
        # message.save()

        try:
            # message = Messages.objects.create(
            #     sent_by=request.user,
            #     media = '🎙 Voice note',
            #     file_type = media_file,
            #     channel_name = channel_name,
            #     message_id = message_id,
            # )
            pass
            content = {
                'data': True,
                'data': True,
                'data': True,
                'data': True,
            }
        except:
            pass

    return JsonResponse(content)

def message_read(request):
    # sleep(1)
    if request.method == 'POST':
        room_channel_name = request.POST['room_channel_name']
        message_delivered = request.POST['message_delivered']
        message_read = request.POST['message_read']
        file_type = request.POST['file_type']
        print(room_channel_name)
        # async_mark_as_read_views.delay(room_channel_name, request.user.username)

        mess = Messages.objects.filter(channel_name__channel_name_main=room_channel_name).last()
        content = {
            'data': False
        }
        if file_type == 'Text':
            mrk_ini = MarkAsRead.objects.get(message=mess, read_by=request.user, media_type='Text')
            mrk_ini.message_read = message_read
            mrk_ini.message_delivered = message_delivered
            mrk_ini.save()

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

chat/templates/chat/public_chat_space.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Whatsapp</title>
  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  <link rel="icon" href="{% static 'images/favicon.ico' %}" />

  <!-- Demo styles -->
</head>

<body>
  <div class="sidebar">
    <div class="main">
      <!-- Main chat window header -->
      <div class="chat-window-header">
        <div class="chat-window-header-left">
          <a href={% url 'chat_zone:index' %}>
            <span class=" icon-arrow_back" id="close_chat_to_menu"></span>
            <img class="chat-window-contact-image" src="{{group_name.cover_image.url}}" />
          </a>
          <!-- <a href="#" id="go-to-user"></a> -->
          <div class="contact-name-and-status-container">
            <span class="chat-window-contact-name">{{group_name.chat_room_name}}</span>
            <span id="room_status" class="chat-window-contact-status">{{group_members}}</span>
          </div>
        </div>
        <div class="chat-window-header-right">
          <span class="icon-video-camera"></span>
          <span class="icon-phone"></span>
          <span class="chat-window-menu-icon icon-ellipsis-v"></span>
        </div>
      </div>
      <!-- Chat window -->
      <div class="chat-window" id="chat-window">
        <!-- New Messages come here -->

        {% for message in chat_messages %}
        {% if message.sent_by == user %}
        <div class="sender">
          <span class="sender-message-tail"><img src="{% static 'images/message-tail-sender.svg' %}" /></span>
          <span class="sender-message">{{message.media}}</span>
          <span class="message-time">{{message.created_on.time}}</span>
          <span class="message-status" id="status_{{message.message_id}}"><img src="{% static 'images/single-check.svg'%}" /></span>
        </div>
        {% else %}
        <div class="receiver">
          <span class="receiver-message-tail"><img src="{% static 'images/message-tail-receiver.svg' %}" /></span>
          <span class="receiver-by">{{message.contact_name_typing}}</span>
          <p></p>
          <span class="receiver-message">{{message.media}}</span>
          <span class="message-time">{{message.created_on.time}}</span>
        </div>
        {% endif %}
        {% endfor %}


        <div id="md-20-spacer" class="md-20-spacer">
          <br>
          <br>
          <br>
          <br>
        </div>
      </div>
      <!-- Type message bar -->
      <div class="type-message-bar">
        <div class="type-message-bar-left">
          <img src="{% static 'images/icons.svg' %}" />
          <img src="{% static 'images/attach-icon.svg' %}" />
        </div>
        <div class="type-message-bar-center">
          <input type="text" oninput="message_text_box(this.value)" id="message_text_box" placeholder="Type a message" />
        </div>
        <div class="type-message-bar-right">
          <button type="button" id="send_message_button" name="button" onclick="send_message_button()">
            <span id="test_voice_note" class="icon-microphone"></span>
            <!-- <span class="icon-send2"></span> -->
          </button>
        </div>
      </div>
    </div>
  </div>
  <div id="snackbar"></div>

  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/md5.js' %}"></script>

  <script type="text/javascript">
    var message_id = ''
    var session_key = md5('chat_app' + Date());
    $('#message_text_box').focus();
    const own_user_number = '{{own_user_number}}'
    const home_channel_name = '{{home_channel_name}}'
    const phonebook = JSON.parse('{{phonebook | safe}}')

    if ($('#message_text_box').val() === '') {
      var tbc = document.getElementById('test_voice_note').setAttribute('class', 'icon-microphone')
    } else {
      var tbc = document.getElementById('test_voice_note').setAttribute('class', 'icon-send2')
    }

    document.getElementById('message_text_box').addEventListener("keydown", function(e) {
      if (e.keyCode == 13) {
        add_message()
      }
    });

    function message_text_box(value) {
      if (value === '') {
        var tbc = document.getElementById('test_voice_note').setAttribute('class', 'icon-microphone')
        user_typing_socket.send(JSON.stringify({
          'status': false,
          'file_type': 'Text',
          'room_channel_name': roomName,
          'home_channel_name': home_channel_name,
          'own_user_number': own_user_number,
          'scope': 'public'
        }));

      } else {
        var tbc = document.getElementById('test_voice_note').setAttribute('class', 'icon-send2')
        user_typing_socket.send(JSON.stringify({
          'status': true,
          'file_type': 'Text',
          'room_channel_name': roomName,
          'home_channel_name': home_channel_name,
          'own_user_number': own_user_number,
          'scope': 'public'
        }));
      }
    }

    function add_message() {
      var message = $('#message_text_box').val().trim()
      message_id = md5(message + Date())
      if (message != '') {
        try {
          document.getElementById('md-20-spacer').remove()
        } catch (error) {}
        let time_stamp = new Date();
        time_stamp = time_stamp.getHours() + ":" + time_stamp.getMinutes()
        $('.chat-window').append("<div class='sender' id=" + message_id + ">" +
          "<span class='sender-message-tail'><img src='{% static 'images/message-tail-sender.svg'%}' /></span>" +
          "<span class='sender-message'>" + document.querySelector('#message_text_box').value + "</span>" +
          "<span class='message-time'>" + time_stamp + "</span>" +
          "<span class='message-status'><img src='{% static 'images/single-check.svg'%}' /></span>  </div>"
        );
        $('.chat-window').append('<div id="md-20-spacer" class="md-20-spacer">' +
          '<br>' +
          '<br>' +
          '<br>' +
          '<br>' +
          '</div>'
        );
        chatSocket.send(JSON.stringify({
          'file_type': 'Text',
          'message': message,
          'message_id': message_id,
          'time_stamp': time_stamp,
          'room_channel_name': roomName,
          'home_channel_name': home_channel_name,
          'own_user_number': own_user_number
          // 'home_channel_name': home_channel_name,

        }));
        document.getElementById('message_text_box').value = ''
      }
      document.getElementById('test_voice_note').setAttribute('class', 'icon-microphone')
      document.getElementById('chat-window').scrollTop = document.getElementById('chat-window').scrollHeight
    }

    function send_message_button() {
      add_message()
    }

    const roomName = '{{room_name}}'
    const home_channel = '{{home_channel_name}}'
    var ws_scheme = window.location.protocol === "https:" ? "wss://" : "ws://"

    const chatSocket = new WebSocket(
      ws_scheme +
      window.location.host +
      '/ws/public_chat/' +
      roomName +
      '/'
    );

    chatSocket.onmessage = function(e) {
      const data = JSON.parse(e.data);
      var contact_details = ''
      for (let i = 0; i < phonebook.length; i++) {
        if (phonebook[i][1] == data.own_user_number) {
          contact_details = phonebook[i][0]
          break
        } else {
          contact_details = data.own_user_number
        }
      }
      try {
        document.getElementById('md-20-spacer').remove()
      } catch (error) {
        //
      }
      if (message_id === data.message_id) {
        // return
      } else if (message_id == '' | message_id != data.message_id) {
        $('.chat-window').append("<div class='receiver'>" +
          "<span class='receiver-message-tail'><img src='{% static 'images/message-tail-receiver.svg' %}' /></span>" +
          "<span class='receiver-by'>" + contact_details + "</span>" +
          "<p></p>" +
          "<span class='receiver-message'>" + data.message + "</span>" +
          "<span class='message-time'>" + data.time_stamp + "</span>"
        );
        $('.chat-window').append('<div id="md-20-spacer" class="md-20-spacer">' +
          '<br>' +
          '<br>' +
          '<br>' +
          '<br>' +
          '</div>'
        );
        message_id = data.message_id
        document.getElementById('chat-window').scrollTop = document.getElementById('chat-window').scrollHeight
        document.getElementById('room_status').innerHTML = '{{group_members}}'

        $.ajax({
          type: 'POST',
          url: '{% url "chat_zone:message_read" %}',
          headers: {
            'X-CSRFToken': '{{ csrf_token }}'
          },
          dataType: 'json',
          data: {
            room_channel_name: data.room_channel_name,
            message_delivered: 1,
            message_read: 1,
            file_type: 'Text',
          },
          success: function(content) {
            // if (content.data) {
            //   console.log('Mark as read passed');
            // } else {
            //   console.log('Mark as read failed');
            // }
          }
        });

      } else if (message_id != data.message_id) {
        $('.chat-window').append("<div class='receiver'>" +
          "<span class='receiver-message-tail'><img src='{% static 'images/message-tail-receiver.svg' %}' /></span>" +
          "<span class='receiver-by'>" + contact_details + "</span>" +
          "<p></p>" +
          "<span class='receiver-message'>" + data.message + "</span>" +
          "<span class='message-time'>" + data.time_stamp + "</span>"
        );
        $('.chat-window').append('<div id="md-20-spacer" class="md-20-spacer">' +
          '<br>' +
          '<br>' +
          '<br>' +
          '<br>' +
          '</div>'
        );
        message_id = data.message_id
        document.getElementById('chat-window').scrollTop = document.getElementById('chat-window').scrollHeight
        document.getElementById('room_status').innerHTML = '{{group_members}}'

        $.ajax({
          type: 'POST',
          url: '{% url "chat_zone:message_read" %}',
          headers: {
            'X-CSRFToken': '{{ csrf_token }}'
          },
          dataType: 'json',
          data: {
            room_channel_name: data.room_channel_name,
            message_delivered: 1,
            message_read: 1,
            file_type: 'Text',
          },
          success: function(content) {
            // if (content.data) {
            //   console.log('Mark as read passed');
            // } else {
            //   console.log('Mark as read failed');
            // }
          }
        });

      } else {
        console.log('Something went wrong');
      }
    }

    chatSocket.onclose = function(e) {
      console.error('Chat socket 1 closed unexpectedly');
    };

    const user_typing_socket = new WebSocket(
      ws_scheme +
      window.location.host +
      '/ws/typing-notification/' +
      roomName +
      '/'
    );

    user_typing_socket.onmessage = function(e) {
      const data = JSON.parse(e.data);
      var contact_details = data.own_user_number + ' is typing'
      for (let i = 0; i < phonebook.length; i++) {
        if (phonebook[i][1] == data.own_user_number) {
          contact_details = phonebook[i][0] + ' is typing'
          break
        }
      }
      if (data.status === true && data.home_channel_name != home_channel_name) {
        document.getElementById('room_status').innerHTML = contact_details
        previous_connection = data.home_channel_name
      }
      if (data.status === false) {
        document.getElementById('room_status').innerHTML = '{{group_members}}'
      }
    }

    user_typing_socket.onclose = function(e) {
      console.error('Tpying indication socket closed unexpectedly');
    };


    const reply_feedback = new WebSocket(
      ws_scheme +
      window.location.host +
      '/ws/reply-feedback/' +
      roomName +
      '/'
    );


  </script>

  <script type="text/javascript">
    '{% if messages %}'
    '{% for message in messages %}'

    var x = document.getElementById("snackbar");
    x.innerHTML = '{{message}}'
    x.className = "show";
    setTimeout(function() {
      x.className = x.className.replace("show", "")
    }, 3000);

    '{% endfor %}'
    '{% endif %}'
  </script>
</body>

</html>

chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>Chat Room</title>
</head>

<body>
  <textarea id="chat-log" cols="100" rows="20"></textarea><br>
  <input id="chat-message-input" type="text" size="100"><br>
  <input id="chat-message-submit" type="button" value="Send">
  <script type="text/javascript" src="{% static 'js/md5.js'%}"> </script>
  <script>
    const roomName = '{{room_name}}'
    var ws_scheme = window.location.protocol === "https:" ? "wss://" : "ws://"
    console.log(md5(roomName));
    const chatSocket = new WebSocket(
      ws_scheme +
      window.location.host +
      '/ws/chat/' +
      roomName +
      '/'
    );

    chatSocket.onmessage = function(e) {
      const data = JSON.parse(e.data);
      document.querySelector('#chat-log').value += (data.message + '\n');
    };

    chatSocket.onclose = function(e) {
      console.error('Chat socket 1 closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
      if (e.keyCode === 13) { // enter, return
        document.querySelector('#chat-message-submit').click();
      }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
      const messageInputDom = document.querySelector('#chat-message-input');
      const message = messageInputDom.value;
      chatSocket.send(JSON.stringify({
        'file_type': 'text',
        'message': message
      }));
      messageInputDom.value = '';
    };

    // const chatSocket_2 = new WebSocket(
    //   ws_scheme +
    //   window.location.host +
    //   '/ws/' +
    //   'home' +
    //   '/'
    // );
    //
    // chatSocket_2.onmessage = function(e) {
    //   const data = JSON.parse(e.data);
    //   alert(data.message);
    // };
    //
    // chatSocket_2.onclose = function(e) {
    //   console.error('Chat socket 2 closed unexpectedly');
    // };
  </script>
</body>

</html>