accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from rest_framework.authtoken import views as api_auth_views

app_name = 'accounts'
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout_view, name="logout_view"),
    path("add-contact-create-group/<int:slider>", views.add_options, name="add_options"),
    path("add-contact/", views.add_contact, name="add_contact"),
    path("add-to-chat/", views.add_to_chat, name="add_to_chat"),
    path("create-group", views.create_group, name="create_group"),
    path('view-profile/', views.view_profile, name='view_profile'),
    path('ajax/check-status/', views.check_status, name='check_status'),
    path("activate/verify-account-sms/", views.verify_account_sms, name="verify_account_sms"),
]

chat/urls.py
from django.urls import path
from . import views

app_name='chat_zone'

urlpatterns = [
    path('', views.index, name='index'),
    path('ajax/upload-voice-note/', views.upload_voice_note, name='upload_voice_note'),
    path('ajax/message-read/', views.message_read, name='message_read'),
    path('public/<str:room_name>/', views.public_room, name='public_room'),
    path('private/<str:room_name>/', views.private_room, name='private_room'),
    path('ajax/111/', views.check_fetch, name='check_fetch')
]

mysite/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('', include('chat.urls', namespace='chat_zone')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/views.py
from .models import Profile, PhoneBook, CurrentlyBindedContact
from mysite.config import OTP_KEY
import pyotp
import base64
from django.shortcuts import render
import re
import string
import hashlib
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import (login as auth_login,  authenticate, logout)
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from accounts.models import Profile
from django.contrib.auth import update_session_auth_hash
from django.utils import timezone
from datetime import datetime
from django.utils.http import urlsafe_base64_encode
from django.contrib import messages
from chat.models import GroupChatRoom, ChannelVilla, ChannelBindingIdentity
from django.http import JsonResponse

def signup(request):
    if request.method == 'POST':
        phonenumber = request.POST['phonenumber']
        country = request.POST['country']
        username = request.POST['username']
        cover_image = request.FILES['cover_image']
        home_channel_name_token = phonenumber + str(timezone.now())
        hash_channel_name = hashlib.md5(home_channel_name_token.encode())
        home_channel_name = hash_channel_name.hexdigest()
        email_address = '%s@whatsapp.com'%phonenumber
        if phonenumber == '' or country == '':
            messages.error(request,'Please make sure phone number and country are provided')
            return render(request, 'signup.html')

        try:
            user = User.objects.get(username__iexact=phonenumber)
            if user.is_active == False:
                add_number = Profile.objects.get(user=user)
                add_number.counter += 1  # Update Counter At every Call
                add_number.isVerified=False
                if cover_image !=  None:
                    add_number.cover_image=request.FILES['cover_image']
                add_number.save()
                rt_valu = str(phonenumber) + str(datetime.date(datetime.now())) + OTP_KEY
                try:
                    key = base64.b32encode(rt_valu.encode())  # Key is generated
                    OTP = pyotp.HOTP(key)  # HOTP Model for OTP is created
                    print('Your OTP is '+OTP.at(add_number.counter))
                    messages.success(request, 'OTP has been sent to your modile device')
                    correspondent = redirect('accounts:verify_account_sms')
                    correspondent.set_cookie('whatsapp_clone', phonenumber , max_age=600)
                    return correspondent
                except:
                    messages.error(request,'Unable to complete Registration')
                    return render(request, 'signup.html')
            else:
                messages.error(request, "Username is already taken")
                return render(request, 'signup.html')
        except User.DoesNotExist:
            try:
                user = User.objects.create_user(
                    phonenumber,
                    email_address,
                    '12345'
                )
                user.first_name = username
                user.is_active = False
                user.save()
                add_number = Profile.objects.get(user=user)
                add_number.mobile = phonenumber
                add_number.location = country
                add_number.home_channel_name = home_channel_name
                add_number.counter += 1  # Update Counter At every Call
                add_number.isVerified=False
                if cover_image != None:
                    add_number.cover_image=cover_image
                add_number.save()
                rt_valu = str(phonenumber) + str(datetime.date(datetime.now())) + OTP_KEY
                try:
                    key = base64.b32encode(rt_valu.encode())  # Key is generated
                    OTP = pyotp.HOTP(key)  # HOTP Model for OTP is created
                    print('Your OTP is '+OTP.at(add_number.counter))
                    messages.success(request, 'OTP has been sent to your modile device')
                    correspondent = redirect('accounts:verify_account_sms')
                    correspondent.set_cookie('whatsapp_clone', phonenumber , max_age=600)
                    return correspondent
                except:
                    user.delete()
                    print('Unable to complete Registration')
                    messages.error(request,'Unable to complete Registration')
                    return render(request, 'signup.html')
            except:
                user.delete()
                print('Something went wrong with request')
                messages.error(request, 'Something went wrong with request')
                return render(request, 'signup.html')
    if request.method == 'GET':
        return render(request, 'signup.html')

def login(request):
    if request.user.is_authenticated:
        return redirect('chat_zone:index')
    else:
        if request.method == 'POST':
            phonenumber = request.POST['phonenumber']
            raw_password = request.POST['phonenumber']
            try:
                profile = Profile.objects.get(mobile__iexact=phonenumber).user_id
                username = User.objects.get(id=profile).username
            except Profile.DoesNotExist:
                messages.error(request, 'User does not exit')
                return render(request, 'login.html')
            user = authenticate(username=username, password='12345')
            user = User.objects.get(id=Profile.objects.get(mobile__iexact=phonenumber).user_id)

            if user is not None:
                try:
                    auth_login(request, user)
                    messages.success(request, 'Login successful')
                    return redirect('chat_zone:index')
                except:
                    messages.error(request, 'Something went wrong with the request')
                    return render(request, 'login.html')
            else:
                messages.error(request, 'User does not exist')
                return render(request, 'login.html')
    if request.method == 'GET':
        return render(request, 'login.html')

def logout_view(request):
    logout(request)
    messages.success(request, "Logged out")
    return redirect('accounts:login')

@login_required
def check_status(request):
    channel_name = request.GET['channel_name']
    try:
        data = Profile.objects.get(home_channel_name=channel_name).avaiablity
    except Profile.DoesNotExist:
        data = None
    content = {
        "data": data
    }
    # print(data)
    return JsonResponse(content)

@login_required
def add_options(request, slider):
    if request.method == 'GET':
        filtered_list = []
        pb_qs = PhoneBook.objects.filter(phone_owner=request.user)
        for user in pb_qs:
            try:
                us = User.objects.get(username__iexact=user.number)
                filtered_list.append(str(us))
            except:
                pass
        contacts = PhoneBook.objects.filter(number__in=filtered_list)
        content = {
        'contacts': contacts,
        'slider':slider
        }
        return render(request, 'add_options.html',content)

@login_required
def add_to_chat(request):
    if request.method == 'GET':
        filtered_list = []
        # chat_channel = []
        channel_name = ''
        us = ''
        pb_qs = PhoneBook.objects.filter(phone_owner=request.user)
        for user in pb_qs:
            try:
                us = User.objects.get(username__iexact=user.number)
                filtered_list.append(str(us))
                try:
                    if us:
                        cbc = CurrentlyBindedContact.objects.get(
                        added_contact_runner=User.objects.get(username=us),
                        app_runner=request.user)
                        # chat_channel.append(str(cbc.channel_name))
                except CurrentlyBindedContact.DoesNotExist:
                    channel_name_token = str(us.profile.home_channel_name) + str(timezone.now()) + str(request.user.profile.home_channel_name)
                    channel_name = hashlib.md5(channel_name_token.encode()).hexdigest()

                    cbc = CurrentlyBindedContact.objects.create(
                        app_runner = request.user,
                        added_contact_runner = User.objects.get(username=us),
                        contact_channel = Profile.objects.get(user=us).home_channel_name,
                        channel_name = channel_name)
            except User.DoesNotExist:
                pass
        # contacts = PhoneBook.objects.filter(number__in=filtered_list)
        # print(contacts)
        # contacts_channel_name = CurrentlyBindedContact.objects.filter(channel_name__in=chat_channel)
        # print(contacts_channel_name)
        contacts_details = User.objects.filter(username__in=filtered_list)
        print(contacts_details)
        content = {
            'contacts_details':contacts_details
        }
        return render(request, 'add_to_chat.html', content)


# 1111
@login_required
def add_contact(request):
    if request.method == 'POST':
        contact_name = request.POST['name']
        phonenumber = request.POST['phonenumber']
        try:
            PhoneBook.objects.get(phone_owner=request.user, number__iexact=phonenumber)
            messages.error(request, "Phone number already exists")
            return redirect('accounts:add_options', 1)
        except PhoneBook.DoesNotExist:
            pb = PhoneBook.objects.create(
                number = phonenumber,
                phone_owner = request.user,

accounts/templates/add_contact.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Whatsapp</title>
  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="swiper-bundle.min.css">
  <link rel="stylesheet" href="fonts/icomoon/style.css">
  <link rel="stylesheet" href="css/styles.css" />

  <link rel="icon" href="images/favicon.ico" />

</head>

<body>
  <div class="sidebar">
    <div class="sidebar-header">
      <div class="app-title">
        Add Contact </div>
      <div class="sidebar-header-icons">
      </div>
    </div>
    <div class="sign_up">
      <div class="signup-type-message-bar">
        <div class="signup-type-message-bar-center">
          <input style="margin-bottom: 2rem;" type="text" placeholder="Enter Name" />
          <input style="margin-bottom: 2rem;" type="text" placeholder="Enter your phone number" />
          <button style="margin-bottom: 2rem;" class="sign_up_button"> Add Contact</button>
          <!-- <button type="button" name="button"></button> -->
        </div>
      </div>
    </div>
  </div>

  <!-- Swiper JS -->
  <script src="swiper-bundle.min.js"></script>

  <!-- Initialize Swiper -->
  <script>
    var swiper = new Swiper('.swiper-container');
    swiper.realIndex = 1
    console.log(swiper.realIndex);
  </script>
</body>

</html>

accounts/templates/add_options.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Whatsapp</title>
  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  <link rel="icon" href="{% static 'images/favicon.ico' %}" />

  <!-- Demo styles -->
  <style>
    html,
    body {
      /* position: relative; */
      height: 100%;
    }

    .swiper-container {
      width: 100%;
      height: 100%;
    }
  </style>
</head>

<body>
  <div class="sidebar">
    <div class="sidebar-header">
      <a href={% url 'chat_zone:index' %}>
        <span class=" icon-arrow_back" id="close_chat_to_menu">
          <div class="app-title" id="app-title">
          </div>
        </span>
      </a>
      <!-- <img src="images/me.jpg" /> -->
      <div class="sidebar-header-icons">
        <!-- <img src="images/search-icon.svg" /> -->
        <span onclick="add_contact()" class="icon-perm_phone_msg"></span>
        <!-- <span class="icon-edit"></span> -->
        <span onclick="create_group()" class="icon-group"></span>
      </div>
    </div>
    <div class="swiper-container" id="swiper_container">
      <div class="swiper-wrapper">
        <div class="swiper-slide">
          <div class="other-feature" style="  margin-top: 0;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
            min-height: 100vh;">
            <span class="contact-name">Add Contact</span>
            <form class="" action="{% url 'accounts:add_contact' %}" method="post">
              {% csrf_token %}
              <input style="margin-bottom: 2rem;" type="text" required name="name" placeholder="Enter Name" />
              <br>
              <input style="margin-bottom: 2rem;" type="text" required name="phonenumber" placeholder="Enter your phone number" />
              <br>
              <button style="margin-bottom: 2rem;" class="sign_up_button"> Add Contact</button>
              <br>
            </form>
          </div>
        </div>

        <div class="swiper-slide">
          <div class="other-feature" style="  margin-top: 0;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
            min-height: 100vh;">
            <span class="contact-name">Create Group</span>
            <form class="" action="{% url 'accounts:create_group' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <input style="margin-bottom: 2rem;" required type="text" name="group_name" placeholder="Group Name" />
              <br>
              <input style="margin-bottom: 2rem;" type="text" name="group_description" placeholder="Group room description" />
              <br>
              <select style="margin-bottom: 2rem;" type="text" required name="contact" multiple>
                <option value="" disabled>Select Contact</option>
                {% if contacts %}
                {% for contact in contacts %}
                <option value="{{contact.number}}">{{contact.contact_name}}</option>
                {{contact.number}} {{contact.contact_name}}
                {% endfor %}
                {% else %}
                <p>None of your contact is on whatsapp</p>
                {% endif %}
              </select>
              <br>
              <input style="margin-bottom: 2rem;" type="file" name="group_image" accept="image/*" />
              <br>
              <button style="margin-bottom: 2rem;" class="sign_up_button" type="submit"> Create Group</button>
              <br>
          </div>
          </form>
          <!-- </div> -->
        </div>
      </div>
    </div>
  </div>
  <!-- SB -->
  <div id="snackbar"></div>


  <!-- Swiper JS -->
  <script src="{% static 'js/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'js/hammer.js' %}"></script>

  <!-- Initialize Swiper -->
  <script>
    var swiper = new Swiper('.swiper-container');
    var slid_check = '{{ slider }}'
    if (slid_check == 2) {
      swiper.slideNext()
    }

    function add_contact() {
      swiper.slidePrev()
    }

    function create_group() {
      swiper.slideNext()
    }
    var myElement = document.getElementById('swiper_container');

    // create a simple instance
    // by default, it only adds horizontal recognizers
    var mc = new Hammer(swiper_container);

    // listen to events...
    mc.on("panleft panright", function(ev) {
      if (swiper.realIndex === 0) {
        // document.getElementById('app-title').innerHTML = 'Add Contact'
      }
      if (swiper.realIndex === 1) {
        // document.getElementById('app-title').innerHTML = 'Create Group'
      }
    });
  </script>

  <script type="text/javascript">
    '{% if messages %}'
    '{% for message in messages %}'

    var x = document.getElementById("snackbar");
    x.innerHTML = '{{message}}'
    x.className = "show";
    setTimeout(function() {
      x.className = x.className.replace("show", "")
    }, 3000);

    '{% endfor %}'
    '{% endif %}'
  </script>

</body>

</html>

accounts/templates/add_to_chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Whatsapp</title>
  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  <link rel="icon" href="{% static 'images/favicon.ico' %}" />

  <!-- Demo styles -->
  <style>
    html,
    body {
      /* position: relative; */
      height: 100%;
    }

    /* body {
      background: #eee;
      font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
      font-size: 14px;
      color: #000;
      margin: 0;
      padding: 0;
    } */

    .swiper-container {
      width: 100%;
      height: 100%;
    }
  </style>
</head>

<body>
  <div class="sidebar">
    <div class="sidebar-header">
      <a href={% url 'chat_zone:index' %}>

        <div class="app-title">
          <span class=" icon-arrow_back" id="close_chat_to_menu2"> Add to Chat
        </div>
        </span>
      </a>
      <!-- <img src="images/me.jpg" /> -->
      <div class="sidebar-header-icons">
        <!-- <img src="images/search-icon.svg" /> -->
        <a href="{% url 'accounts:add_options' 1 %}">
          <span class="icon-add"></span>
        </a>
        <!-- <span class="icon-edit"></span> -->
        <span class="icon-ellipsis-v"></span>

        <!-- <img src="images/menu-icon.svg" /> -->
      </div>
    </div>
    <div class="chats">
      <a href="{% url 'accounts:add_options' 1 %}">
        <div class="chat">
          <div class="chat-left">
            <img src="{% static 'images/default_image.jpg' %}" />
          </div>
          <div class="chat-right">
            <div class="chat-right-top">
              <span class="contact-name">New Contact</span>
            </div>
          </div>
        </div>
      </a>

      <a href="{% url 'accounts:add_options' 2 %}">
        <div class="chat">
          <div class="chat-left">
            <img src="{% static 'images/default_group_image.jpg' %}" />
          </div>
          <div class="chat-right">
            <div class="chat-right-top">
              <span class="contact-name">Create Group</span>
            </div>
          </div>
        </div>
      </a>

      {% for user_detail in contacts_details %}
      <a href="{% url 'chat_zone:private_room' user_detail.profile.remote_channel_name %}">
        <div class="chat">
          <div class="chat-left">
            <img src="{{user_detail.profile.cover_image.url}}" />
          </div>
          <div class="chat-right">
            <div class="chat-right-top">
              <span class="contact-name">{{user_detail.profile.contact_name}}</span>
            </div>
            <div class="chat-right-bottom">
              <div class="chat-right-bottom-left">
                <span class="chat-message">{{user_detail.profile.about}}</span>
              </div>
            </div>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
  <!-- SB -->
  <div id="snackbar"></div>

  <script>


  </script>

  <script type="text/javascript">
    '{% if messages %}'
    '{% for message in messages %}'

    var x = document.getElementById("snackbar");
    x.innerHTML = '{{message}}'
    x.className = "show";
    setTimeout(function() {
      x.className = x.className.replace("show", "")
    }, 3000);

    '{% endfor %}'
    '{% endif %}'
  </script>

</body>

</html>

accounts/templates/create_group.html
{% load static}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Whatsapp</title>
  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}" />
<link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}" />
<link rel="stylesheet" href="{% static 'css/styles.css' %}" />

<link rel="icon" href="{% static 'images/favicon.ico' %}" />

</head>

<body>
  <div class="sidebar">
    <div class="sidebar-header">
      <div class="app-title">
        Create Group </div>
      <div class="sidebar-header-icons">
      </div>
    </div>
    <div class="sign_up">
      <div class="signup-type-message-bar">
        <div class="signup-type-message-bar-center">
          <input style="margin-bottom: 2rem;" type="text" placeholder="Group Name" />
          <input style="margin-bottom: 2rem;" type="text" placeholder="Group room description" />
          <input style="margin-bottom: 2rem;" type="file" accept="image/*" />
          <button style="margin-bottom: 2rem;" class="sign_up_button"> Create Group</button>
          <!-- <button type="button" name="button"></button> -->
        </div>
      </div>
    </div>
  </div>

  <!-- Swiper JS -->
  <script src="swiper-bundle.min.js"></script>

  <!-- Initialize Swiper -->
  <script>
    var swiper = new Swiper('.swiper-container');
    swiper.realIndex = 1
    console.log(swiper.realIndex);
  </script>
</body>

</html>

accounts/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Login</title>
  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}" />
  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}" />
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

  <link rel="icon" href="{% static 'images/favicon.ico' %}" />


</head>

<body>
  <div class="sidebar">
    <div class="sidebar-header">
      <div class="app-title">
        Login </div>
      <div class="sidebar-header-icons">
      </div>
    </div>
    <div class="sign_up">
      <div class="signup-type-message-bar">
        <div class="signup-type-message-bar-center">
          <form class="" action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            <input style="margin-bottom: 2rem;" type="text" id="number" name="phonenumber" placeholder="Enter your phone number" />
            <button style="margin-bottom: 2rem;" type="submit" class="sign_up_button"> Login</button>
          </form>
          <a style="width: 4rem;" href="{% url 'accounts:signup' %}" class="sign_up_button"> Sign Up</a>
        </div>
      </div>
    </div>
  </div>
  <div id="snackbar"></div>

  <script type="text/javascript">
    document.getElementById('number').focus()
  </script>
  <script type="text/javascript">
    '{% if messages %}'
    '{% for message in messages %}'

    var x = document.getElementById("snackbar");
    x.innerHTML = '{{message}}'
    x.className = "show";
    setTimeout(function() {
      x.className = x.className.replace("show", "")
    }, 3000);

    '{% endfor %}'
    '{% endif %}'
  </script>
</body>

</html>

accounts/templates/otp-waiting.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Register</title>
  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}" />
  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}" />
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

  <link rel="icon" href="{% static 'images/favicon.ico' %}" />
</head>

<body>
  <div class="sidebar">
    <div class="sidebar-header">
      <div class="app-title">
        Add Contact </div>
      <div class="sidebar-header-icons">
      </div>
    </div>
    <div class="sign_up">
      <div class="signup-type-message-bar">
        <form class="signup-type-message-bar-center" method="post" action="{% url 'accounts:verify_account_sms' %}">
          {% csrf_token %}
          <div class="">
            Please enter OTP code
          </div>
          <input style="margin-bottom: 0.5rem;" type="text" name="otp" placeholder="Enter OTP" />
          <button style="margin-bottom: 0.5rem;" class="sign_up_button"> Validate OTP</button>
          <!-- <button type="button" name="button"></button> -->
        </form>
      </div>
    </div>
  </div>
  <div id="snackbar">
  </div>
  <script type="text/javascript">
  </script>
  <script type="text/javascript">
    '{% if messages %}'
    '{% for message in messages %}'
    var x = document.getElementById("snackbar");
    x.innerHTML = '{{message}}'
    x.className = "show";
    setTimeout(function() {
      x.className = x.className.replace("show", "")
    }, 3000);

    '{% endfor %}'
    '{% endif %}'
  </script>
</body>

</html>

accounts/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Edit Profile</title>
  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}" />
  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}" />
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

  <link rel="icon" href="{% static 'images/favicon.ico' %}" />

  <!-- Demo styles -->
  <style>
    html,
    body {
      /* height: 100%; */
    }

    .swiper-container {
      width: 100%;
      height: 100%;
    }
  </style>
</head>

<body>
  <div class="sidebar">
    <div class="sidebar-header">
      <div class="app-title">
        Whatsapp </div>
      <div class="sidebar-header-icons">
      </div>
    </div>
    <div class="sign_up">
      <div class="signup-type-message-bar">
        <div class="signup-type-message-bar-center">
          <input style="margin-bottom: 2rem;" type="text" placeholder="Enter username" />
          <input style="margin-bottom: 2rem;" type="text" placeholder="Enter your phone number" />
          <input style="margin-bottom: 2rem;" type="file" accept="image/*" />
          <button style="margin-bottom: 2rem;" class="sign_up_button"> Update</button>
          <!-- <button type="button" name="button"></button> -->
        </div>
      </div>
    </div>
  </div>
</body>

</html>

accounts/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Register</title>
  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}" />
  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}" />
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

  <link rel="icon" href="{% static 'images/favicon.ico' %}" />


</head>

<body>
  <div class="sidebar">
    <div class="sidebar-header">
      <div class="app-title">
        Register </div>
      <div class="sidebar-header-icons">
      </div>
    </div>
    <div class="sign_up">
      <div class="signup-type-message-bar">
        <div class="signup-type-message-bar-center">
          <form action="{% url 'accounts:signup' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input style="margin-bottom: 2rem;" type="text" name="country" placeholder="Select Country" />
            <input style="margin-bottom: 2rem;" type="text" name="phonenumber" placeholder="Enter your phone number" />
            <input style="margin-bottom: 2rem;" type="text" name="username" placeholder="Enter username" />
            <input style="margin-bottom: 2rem;" type="file" name="cover_image" accept="image/*" />
            <button style="margin-bottom: 2rem;" class="sign_up_button"> Register</button>
          </form>
          <!-- <button type="button" name="button"></button> -->
          <a style="width: 4rem;" href="{% url 'accounts:login' %}" class="sign_up_button">Login</a>

        </div>
      </div>
    </div>
  </div>
  <div class="" id="snackbar">

  </div>
</body>
<script type="text/javascript">
  '{% if messages %}'
  '{% for message in messages %}'
  var x = document.getElementById("snackbar");
  x.innerHTML = '{{message}}'
  x.className = "show";
  setTimeout(function() {
    x.className = x.className.replace("show", "")
  }, 3000);

  '{% endfor %}'
  '{% endif %}'
</script>

</html>